# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96018cf9a773c98826c4087d0fe4b2ba3a91d2345d1929590227025b6b19b4ae5f2a970b596fd470627add55d918c24ac54b69e98f66309df2b2c019fa5cb0ba

test:
  secret_key_base: fa458ee3f96458a6110cbd37fed8281b841ca2907a42fb08955b4575260ecc27df417ca1379c1c3a8db35c069241a14ee627c16a9a0144edc41c88dd284294db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
